version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: mati
      POSTGRES_PASSWORD: 1701
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0' -p 3000"
    volumes:
      - ".:/app"
      - gem_cache:/usr/local/bundle
    ports:
      - "5000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://mati:1701@db/myapp_development
      REDIS_URL: redis://redis:6379  # Añadido para la conexión de Redis

volumes:
  gem_cache:
  db_data:
