default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
<<<<<<< HEAD
  username: julia
  password: 1234
=======
  username: capi
  password: 3464
>>>>>>> temp-branch
  host: db # Este es el nombre del servicio en docker-compose.yml


development:
  <<: *default
  database: app_development


test:
  <<: *default
  database: app_test


production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>

